### ISSUE TITLE
Is it possible to delete data points?

### ISSUE THREAD

**Issue by vilisseranen** [ytyou/ticktock#57]
I don't seem to be able to delete data points. OpenTSDB doc says `tsd.http.query.allow_delete` needs to be set to true but I don't see such option in the ticktock config. Any suggestion?

**Comment by ylin30** [comment]
@vilisseranen Unfortunately TT doesn't support deletion yet. We don't have a plan to support it since we don't see very compelling uses cases for deletion, at lease for the time being. 

According to our understanding, deletion may be used to

1. save disk spaces
2. correct a data point due to human mistake

To solve 1, TT saves data in many folders, one per TSDB ordered by time range (default 1 tsdb for 1 day). So you can just delete outdated TSDB folders or move them to other disks for backup, to save disk spaces.

To solve 2, you can reinsert a data point (with same time series and same timestamp) with a different value. TT will override the old data point with the new one, instead of adding a new data point at the same timestamp.

Please let us know if the two cases fit your cases, or you have a good reason to support explicit deletion.

**Comment by vilisseranen** [comment]
Thank you for your answer. I think I can work with solution 2.

Just for context, I am using ticktock on an orangepi zero2 and I use it to store the temperature for different sensors I have in the house. Sometimes a sensor will send some bad data. I guess I could also filter the data before storing them in ticktock.

**Comment by ylin30** [comment]
> Just for context, I am using ticktock on an orangepi zero2 and I use it to store the temperature for different sensors I have in the house. Sometimes a sensor will send some bad data. I guess I could also filter the data before storing them in ticktock.

By 'bad', do u mean bad format or bad value? If the former, just send them to TT and TT should be able to reject them.

**Comment by vilisseranen** [comment]
I meant bad value. For example it's 20degres in the room and the sensor for some reason sends -5degres.
