### ISSUE TITLE
Installing the TickTockDB Demo in Docker fails on a RaspberryPi model 2 with the 32 bit version of Bookworm 

### ISSUE THREAD

**Issue by juggledad** [ytyou/ticktock#71]
I followed the directions in the ReadMe and get all the way to the end however the ticktock:latest-grafana points to a 64 bit version

pmw@dockerpi:~ $ sudo docker run -d --name ticktock -p 3000:3000 -p 6181-6182:6181-6182 -p 6181:6181/udp ytyou/ticktock:latest-grafana
Unable to find image 'ytyou/ticktock:latest-grafana' locally
latest-grafana: Pulling from ytyou/ticktock
76769433fd8a: Pull complete 
b658d5695fae: Pull complete 
c467919ea0e7: Pull complete 
a75884a1ca9f: Pull complete 
86006b9b337f: Pull complete 
137b558371e5: Pull complete 
09305ca2cd2b: Pull complete 
69fc7cd00537: Pull complete 
a44d8a58e254: Pull complete 
4f4fb700ef54: Pull complete 
Digest: sha256:0be5c3face65575aa4590665cc954292d36d1f049f753091cecd26ab65e014da
Status: Downloaded newer image for ytyou/ticktock:latest-grafana
**WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm/v7) and no specific platform was requested**
9f5f6f7b26bec270cff41113ae716d7e6adc15ab248c950af918bc39baea0390

is there a way to get the 32 bit version?

**Comment by ylin30** [comment]
Unfortunately all our docker images are in 64 bit right now. @ytyou Can u prepare a 32-bit version of docker image?

@juggledad The docker image has both TT and Grafana. As a work-around, you can still download and install the prebuilt 32 bit version of TT in RPI2: [ticktockdb-0.20.0-beta-glibc2.28-armv6l.tar.gz](https://github.com/ytyou/ticktock/releases/download/v0.20.0/ticktockdb-0.20.0-beta-glibc2.28-armv6l.tar.gz), and use Grafana installed in another machine. You just need to redirect the data source in Grafana to TT in your RPI2.

**Comment by ytyou** [comment]
I created a 32-bit version of the docker image that contains TickTockDB only (Grafana is not included). Please use the "0.20.0-beta-32bit" tag to launch the docker image.

**Comment by ylin30** [comment]
@juggledad FYI Grafana annouced that its 32 bit version in ARM has been paused due to a bug in Go compiler, according to this [blog](https://grafana.com/blog/2023/09/29/grafana-and-grafana-enterprise-updates-for-armv6-and-armv7-will-be-temporarily-paused/). So we can't prepare you a 32 bit docker image with Grafana but only with TT. 

You can work around it by connecting a Grafana (in 64 bit machine) to a remote TT (in 32 bit) by updating data source in Grafana. Please refer to the attached pic for instructions. 

![image](https://github.com/ytyou/ticktock/assets/6943113/cd404791-e230-4d7e-8a4e-7c89581c8f7e)
